server:
  port: 10089
  servlet:
   contextPath: /dde
spring:
  application:
    name: DDE
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.18.10.212:1521/TZXMSPPT1.datasx.com
    username: tzxmsp3
    password: tzxmsp3_123
    dbcp2:
      max-wait-millis: 10000
      max-idle: 15
      initial-size: 10
      validation-query: SELECT 1 from dual
      connection-properties: characterEncoding=utf8
centit:
  useDataMoving: false
  dataMovingPath: D:\centit-dde-datamoving-3.0-SNAPSHOT.jar
  logs: D:/Projects/RunData/dde/logs
framework:
  app:
    home: D:/Projects/RunData/dde
  ip:
    enable: true
    topoptid: DDE
    home: http://192.168.134.2:11000/framework/system
    auth-enable: false
    usercode: admin
    password: 000000
logging.path: D:/Projects/RunData/dde/log
os:
  file:
    base:
      dir: D:\D\Projects\RunData\file_home\export





